var Box_answer=['DULLRUUDRR',
'RRDDDDRDDLLURDRULUUUUULLDRURDDDDRRRDRUUDLLLDDLLURDRULUUUULLDRURDDDRRRDRULLLDDLLURDRULURRR',
'RRRDDRRUULUULLLLDDDUUURRRRDDLLLRRRUULLLLDDLDRURDURRDDRURULLLLRRRUULLLLDDLDRURRRRRRULDLLLLLUURRRRDRDLLLLRRRUULLLLDD',
'RDRDRDDLLRRUULDLDRUUULDDUUUURDDDD',
'RDRRDDRDDLLULLDLURRRDLLRRRRUULUULLDDUURRDDRDDLLULL',
'LLLLLDLLLLUURRRURUULURRLDDDLDLLLULUUUURRRURRRRDDLLDLLDLUUDRRRDRDDULLDLLLDDRRRRURLDLLLLUUULUUUURRDDDRDRDLLRURRRDDLDLLLLUUDDRRRRURRRDRRULLLL',
'DDDLULLULLDDDUUURRDRRDDDLLULDLLRRRRRUUULLULLDDDRDLUUUURRDLDDLDRUUURRRRUULDRDLLLULDDDUUULDDD',
'LLLDLLLRUDRRULLLRRRRRUULLLDLDDRRULLRRRRDLLLL',
'LULULLDDRULURDRRDRRULLLULLDDRUDLLLLURUUURURRRURRDDDDUUUULLDRLLLLDLDDDRDRUURDRRDRRULLLRRUUULUURDDDDUUULLLLLDLDDDDRRRUUDRRDRRULLLRRUUUULLLLLDLDDDDRRRULLLUUURUULDDDDUUURRRRRRDDDDLLLDLLLLURRDRU',
'DRRRURRUULLDDLDLLURRRUURRDLULDULDD',
'ULLLDLLLURRRLLUULDLDRRDRRURRDRRULLLRRRRUULDRDLLLRRUULDRDL',
'DLLDLLURRURRDDLLDDRRUDLLUUULLDR',
'LUURRUUDLLDDDRRUUDDRRULDLLLUURRURDLLLDDRRUURULDDDRUULLUU',
'DRLUURDRRULRURRDLLDDDRRULULUURRDLDLLLLUURDLDRRLLDDRULUR',
'UULUURRDLDDDLURUUULLDRLLDDRRDRULULUURDURRDLRRDDLLULRDDLURURUULDULLDRRURD',
'LLUULUURLDDRULUUURRDLULDDDUURRRRRDDLLLLLLRRDLLRRDDRRUURULLLLUURRDLULDDRDLRDDRRRUULULLULDUURRRRRDDLLLL',
'LUULUURRRDDRDLUUULLDRURDDRDDRRULDLUDLUDLLURRLLULURURRDDUULLDRURD',
'RUULUURUULDLLULLDRRRRURDLDDDRDDLULLUUUDDDRRUUUULLULLDDRLURRRRDDDDLLURDRUUUDDLLUULURDLLLDDRRRRDRUU',
'LULLUDRRURUDLDDRRURRUULLRRDDLLDLLUULUURURRDLULLDDDDLLURDRUUUDDLLURDRUDRRUURULDDDLDDRRURRUULLRRDDLLDLLUURUUDRRRDDLURULLRDDLDLLUURU',
'RUULURUULLLDLDDRUULDDDDRUUURRUDDRUUDDDDLUUUDLLDLUUDDRRRDRUUU',
'UURDRRDRRUUURULDDDDLLURDRUUUDDLLLLLDDRULURRRRDRUUDDRUUULLRDDLLLLDDRULURRRDRUURULRDDDDRRULDLUUUDDRRULLDLUU',
'ULUULLULLLUURRDURDRRDDDRDDLLULLDLUUUDDRRRURULDRRDLLLLDLUU',
'LLLUULLDDRDDLDRRLUUULUURDDDDLDRUUUULLLDRRURDDULDDRRLUUURRDLULDDLDRUURRRRULLLULDDDD',
'LLLDLLURRRRDRULLLLLULLDRRRRRRRLLLLLLLUUULLLDDDRRRRRRRRRDRRUUUDLDLLLLLLLLDDRULURRRRRRRRLLLLLLLDRLDDRRRRUULURRRURRDDDULULLLDDDLUUDDLLUURURRRRRURDDULLLLDDLULURRRRRLLLLLULLDRRRRRRDRRUULDLLLLLLLLLLUURRURDLDRULLLDDRRRRRRRRRRLLLLLUULDLDRRRRRRDRULLLLLLLLUUURDDLDRRRRRRRURDD',
'RRUURRRUUUUDDDDLLLUULUURDRRDRDDLLLUULURRLDDDRRRUUURRDDRDDLULLUULULLDDDRRDRULLLUUURRRRRDDRDLLLUULULLDDDDDLLUURLDDRRUUUULURRLDDDRRDRUU',
'LLLDDLLUUDDRRUULUURURRRUUULLLDDRDDLLDDRRRRUUULLULDRRRUURULLLULDDDLDRRLUUURRRDDDDDDLLLLULLLDLLURUURRRRRUUURRRDDDDDDLLLLUUDDRRRRUUUUUULLLDDDLLRDDLLLDLLURRRRDRUUDDRRRRUUUUUULLLLLLULLDRRRRRDDDLDDLLLLUUURUDLDDDRRRDRRDDLLUURRRRRUUUUUULLULDDDUULLLULLDRRRRLLLDDLDDDRRRDRUUDDRRRRUUUUUULLULDD',
'RUUUUUURUDLLURRLDDDDDDRRULDLUUUUULUUURRRRRRDDDLLLDDLRUULDLDDDRDLLLLLLRUUULLLDDDDRUUUUDDDRRRRRRUUUURRDLULDDDRDLLLLLLRUUULLLDDDDRUUDRRRRRRUUURUURRRRDDLLLLULDDDRDLLLLLLRUUULLLDDRULDDDRUUDRRRRRRUUURRRRRUUUUULLLLDDDUUULLDDRLUURRDDLDDDDDRDLLLLLLLDLUUUURRLLDDDRRRRRRRUUURRUULUUURRDDLRUULLDDLDDDDDRDLLLLLLRUURUULDLLLDDDDRURRRRRRUUURRUULULDDDDDRDLLLLLLLDLUUUDDRRRRRRRUUURRULULDDDDRDLLLLLLLDLUUDRRRRRRRUUURRRRRUULLLLULDDDDDRDLLLLLLLDLURRRRRRRUUUUURRRDURRDDLLLLULDDDRDLLLLLLLRRRRURDRUUURUULDDDDRDLLLLLLRUURULL',
'URRDRRRRURDRRUURRLLDDDDRRUUUULLDDLLLLLLLUURDLDRRRRRRDRURURDDDUULLLLLLLLUUURDDLDRRRRRRLLLLLUUUUULDDDDLDRRRRRRURRLDDRURDUUDLLLLLLLULLLLDRRRRRRRRRLLLLLDDDLULULURRRRRRRLLLLDDLULURRRRDRRRRLUURDDLLLULLLDDDDDLUUUULURRRRRRRRLLLLLLDDDDLLULLDRRRDRUUUULURRRRRRLLLLLUUUULLDDDLDRRRRRURRRLLDLLLUUULLLLURRRURDDDDLDRRRRRLLLLULLLLURUULLDRRRDDLDRRRRRDRRRLLULLLUUUULDDDLDRRRRURRLDLLLDDDLLUULURRRRRDRRLULLLLLLLDDRDDLLURRRUULURRRRRRLLLDDDDLUUULURRRRURDLDR',
'LUUURULLRDDDDRRULDRRRULLDLLUUULLDRURRURRDDLDDLLUULUURRLLDDRULURDDDDRRRUUUDDLLDLUUUDDDLUUU',
'DDRRRRRRRUULLLLLLUURRRDULLLDDRRRRLLLLULLDRDDRRRRUDRRRUUURULLLRRDDDDLLLLLLLUURDLDRRR',
'DDDLDDLLULURDDRRUURUUULLLDDDLLLUURRLLDDDRURRUURURRDDDLLLUURRURDLLLDDRRDDLLUULLDRLLU',
'LUUUULURRDLDDDDRRRUULLRUDRDDLLLUUUURULDDDDDLLUURLDDRRUUUDRUUL',
'DRRRUUULLULUURRURRRDDLLDDDDRDLLLULDRRRUUULLURLLUURRDRDDDDRDLLLDLLDLURRURRRUUULLURLLURURDRDDDDRDLLLULLRDDURRRUUUUURRRDDLLRRUULLLDDDDRDLLLDDLLRUURRRUUUUURRDRDLLRUULLDDDDRRUDLDLLLULDDRDLRRRRUULUUUUURRRDDLLRUULLDDDDUURRDDLDLLLULDRRRRURUULLDDRDLLDLLLRUURDRRURRUUURRRRDLLLLLRUULLDDDDRDLLDLLUURDRRUUUUULUURRDRRRDDRDLLLLRUULLDDDDRDLLLULDDURRRUUURRRRRRUULLLULDDRDLLRUULLDDDDRDLLLULDRRRUUULLURLUURDRDDDDRDLLLRRUUULLURURDDDDRDLLRRDDLL',
'DLLLDDDRRURRRRDRRUUDDLLURLLLLUURDLDRRRLLLUUUULUUUUURRRDDDDDLDDUUURRRDDLLDLDLDRRDRRRRRRRUUUUUUUULLLLLDURRRRRDDDDDLLDLDDLLLLLUUURURRURULLRDDLLULDDDUUULLUUUUURRRDDDDDURRDDLLRRUUUUUURDURRRRDDLLLLULDDURRRRRDDDDDDDDLLLLLLLLLURUURURRURULLRUURRRRRDDLURULLLLULDDURRRRRDDDDDDDDLLLLLLLLUUURURRURULUUUURRRRDRDLLLLULDDDDUUURRRRDDLURULLLULDDURRRDDDLDDRRRDDDLLLLLLLLLUUUUULUUUUURRRDDDDDLDRLDDULLLLUURRRLUUURRLLUURRDRDDDDULDDULLLLUUUURURDDRRURDDULLLDDULLDDRDLDRRLUURRDD',
'LULUULLDDRDDUULUURRDRDDRRURUULDLLDDRRURULDDDDRRDDLLUULLLDLLURUUURLLUURRDULLDDRDDDRRRRDDRRUULLUUURUULDLLDURRDDDDRRDDLLUUUDLLLDLLURRRRRDDRRUULRDDLLUULLLLUUURLLUURRD',
'DDRLURRUULULUURRDDLDRULLURURDDDDRDRUURRRRDRDLLLLLDDDRRRDRUUUDDLLLLUUUUURRRRDRDLLLLRRRUULLLLULDLLUURDDUUULLLLLDDRDDDDDDRRRRRRRRRDRUUUDDLLLLUUUDDDLLLLLLUUUUUURRRURDRDRRRRRDRDLLLLRDLURRRUULLLLULLLDRRLUUULLLLDLDRRRRURDLDRULLLLURRRURDD',
'LDDRRDDLLRRUULLUURRDDDULLDDRRLLULLLDDRULURRLDRRUURRDDLLLRRRUUUULLDDDLDRULLLDRURRURRULULDD',
'RDDRRRRRUULURLLUURRDLDDRDRRUUUUUUUULLLLDDRDDLURULLLLRRRUURRRRDDDDDDDDLLULULUUURULLLULDRRRDDRRDLDLUUURULLLDLLUULDDRRURRRUURRRRDDDDLLLDLUURULLLLRRRDDRRRRDLLLDLUUURULLLULLDLURRDRRRRDDDDDRUDDDLLLLLUUURRLLDDDRRUUDDRRRUULLUUUURULLLLDLURRRRDDRRRDLLDLUUURULLLLLRRRRDDRRRRDDLLLDLUUUURULLLLRRRDDRRDDDDDLLLLLUUURRLLDDDRRUURUUUURULLLULLDDRURRRDDDDDLDDLLUUURRDRUUUURULLLLRRRDDDDLLLDDRULURRDRUUUURULLLULDRRRDDDDLLDDDRUULURDRUUUURULLLDLUU',
'LUUULULLLLLUUURRDDUULLDDDRRRDRRRDDDLLLLLUUURUUUULLDRURDDDUURURRDDDUUULLDRURDDULLLLLDDRDDDDRRRUUDLLDLUUUDDDRRRRRULLLLDLUU',
'RDDDRRUURRDDDDUUUULLDDRLLDDRRRUUDDLLLLDDRULURUULDDUURRUULULDDDRRRRDDLDRRRURRRRUUURUULDLLLLLLLLDDRRDDDRRURRRRUUURULDDDDLLURDLLLURRDDLDDRRDDLURULDLLDLLUURDRRUUURUULDDDDRDLLLLULDDRRURRUUUURRRUUURUULDLLLLLDDLLLLDDRRDRRRURDDDRDLLDLLUURDDURRUUULLLLULLUURRRDDLDRRRURDDDRDLLDLLUURDRRUUULLLULLLDDLLURDRULURRRLLUURRRDDLDRRRURDDDRDLLLULDDRURRUUULLLUUULLLLDDRDDLLURDRULURRRLLUURRRDDLDRRRURDDDRDLLLLRRRUUULLLUUULLUULULDDDDDRDDLLURDRULURRRLLUURRRDDLDRRRURDDDRDLLLULLDRURDRRUUULLLUUURUULDDDDUUUULLLULDDDDDRDDLLURDRULURRRDRRRURDDDRDLLLULDRRRUUUURRRUUURULLLLLLLDDDDUUUULLLULDDDDDRDDLLURDRULURRRDRRRURDDDRDLLLLRRRUUUUURRDRUUURULLLLLLLDDDDUUUULLLULDDDDDRDDLLURDRULURRRDRRRURDDDRDLLLRRUUULLLLULLUURRRDDLDRRRURDDDRDLL',
'UUULDURRUULLDLLLLDDRDDLLURDRULUUURRRRURRDDLDLURDDDLULLUUDDRRRUULLULRDRRDDLLLUUDDLDLLURURLDDRURRRURULLRRRUULLDURRDDLL',
'RDDDDLLUULLRRDDRRUUUULLLULDLLLLULLDRDDRRRDDLLULUUURRRRRDDRRDDLLLLUURLDDRRRRRRUULLRUULLULDLLLLLDDRRRDDLDLUULURRLLUURRD',
'DRDDLLLDLLDDRDDLUUUURUUDLDDDDDDLLULUURRLLDDRRURUUUUUDDDDDRRRDLDLLUUUUUUDDDDDLLLURRLDDDRURUUUUULUURRDLDDDDRRDLRRRDLLLLUUUUUUDDDDRRRURDULLLDLUUULURDRURUDRRRRDDDRDLLLLLLDLUUUULURRDRURRDRURDDDRDLLLLDDRULULLDLUUUULURRRRRDRRDDDLLLLLDLUUUDDRRRRRRUUULLULLLLLDRRLDDDLLDRLDDRURUUUUDDRRRRRRUUULLULLLLLDRDDDLLURDRUUUDDDRRRRRRUUULLULLLLDDDLLDDRDRUUUUUDDDLLLLLURRRRDRUUDDRRRRRRUUUULLLLRRRUULDRDLL',
'LLDLDDDRRLLUURUURRURRDLDDRRDDLLDDLLUULLUURUURRURDLLLDLDDDRRDDRRUULRRRUULLDURRDDLLRRURRULUULLULLDRDDDURRDRRULUULLULDDDUURRRDDLL',
'LDDRRRUUUUUDDRRDDRRRUUUULRRRRUUDDLLLDDDDLLLUULLDDDLLLUURRLLDDRRRUUUUDDDDLLULURRLDDRRUUURRDDRRRUUUULULLDDUURRDLDURRRRRUURUULDDDUULLULLLDDDDRRDDDDLLLUUDDRRRUUUURRDRRULLLLLULUUURRRDDLURULLULDDDUURRDRRRDDDLLLLULUUURRDLULDDURRRRRDDDLLLDDDDLLLUULLDLLDRDRULLLUUURDLDRURRRLLLDDRULURRLDDRU',
'UUUUUURLDDRULDDDRURRLLLUURRRDRDRRRDDLDRDLDRRDULLDRDRRRRLLLLLLRUULDLLLLUUUULUURRRRRRURDDDDDDRDLDRRRLLUULLDLLLLLUUUUULURRRRRRURDDDDDURDDRRDRLULDULLLDLLLLLUUUURULURRRRRURDDDDDDDRRRLLLLLLLLLUUUURRULURRRDLRURURDDDDDUUURRULDDDDDLDRRLLLLLLLLUUUURRURURRURDDDDDLDRDLLRRUUUUUULLDLLLURRRRURDDDDDDUUUUULLLLUULLDLDRRRRRRURDDDDDRDDLLURUUUUULLLLUULDLDRRRRRURDDDDDDUUUUULLLLLLLUUUURDDDLDRRRRRRURDDDDDRDLUUUUULLLLUUULDLLUURDDDLDRRRRRRURDDDDDLDRUUUUUULLULDLDRRRURDDDDDUUUULLLLLUUURDDLDRRRRURDDDDRRDDURLLUUURDDDUURDDLLLULD',
'LDDRDDRRURRRRRUULLLLULDRRRDURRDDLLRDDRDDLULLDLUUULLLDLDDRURRRUULLLDLDRUUUULUURDRRDDUURRRDDRDDRDDLULLDLLURUULUUURRRDDRRUULLLLULDDDUULLDDDDLDDRURRDRUUDLLLUUUULUURDRRRRRDDRDDRDDLULLDLULLLUUUULUURDRRRRRDDRDDRDLLLDLLULLUUUULURRLDDDDDRRDRRULLLRRRRRUUULUULLULDDULLDDDDLDDRUUUUULURRLDDDDDRRRRRRUUULUULLULD',
'LDDRDRDDLUDDLLLUURRRRUULDULUURDURDDDLDLLLDDRUDRRURUDRDRRULLDL',
'UUUUUUUUURDRDRDRRURURRRLLURRDLLLDLDDRDRRRLLLULULLURURRRRLLLURRRDLLLLDLLURRRRRLLLLURRRRDLLLLLLURRRRRDDDRRRLLURRLLLULLDRRRRLLULLLLLLDRRRRRRRLLLLLLLDDRULURRRRRRLLLLLDRRRRRRRLDRRLULLLDRRRLLDRRLDRRDDDLULURRLLLURRUUULLLLLLLLDDDRURRDRRRRLLLDRRRRLLLDRRRRLLLDRRRLLUUULLLLULLDRRRRRLLLLDRRRRRLLLLDRRRRRLLLLDRRRRLLUUULLLLLLDRRRRRRLLLLLDRRRRRRLLLLLDRRRRRLLLLUUUUURRRRLLDRRLLDLLURRRLLLLLURRRRRLLLLURRRRRLULLLLLLDRRRRRRDDDLDLDRRLLLLLLDRRRRRR',
'DRULUUURRDDLRUULLDDRDDLLLUURRDUUURRDDLRUULLDDLLDDLLUURRRRUURRDDLDDLLLUURRDUUURRDDLDDLUULLDDDDRRUUDDDDRRUULRDDLLUULLUUUULLDDLLUURRDDDDRRUULLUULLDDDDRRUULRRRUURRRDDLLLDDRRUDDDRRUULRDDLLUULLUULLDDRRLLLLUULLDDRRRRUULLRRRRUURRRDDLLLDDRRUDDDRRUULRDDLLUULLUULLDDRRUUUURRRDDLLLDDLLUUUURRDDDDLLLLLLUUUURRRRDDDDLLUULRDDRRUULLDDRRRRUULLLRRRRRRUULDRDLLLLLRRRRUURRUULLDDDRDLLLUURLDDDDLLUUUURRDDLRDDLLUURRRRRUURUULLDDDRDLLLLRUURLDDRRRUURUULLDDLLDDDDRRUDLLUUUURRRDDLLLRRDDDDRRUULRDDLLUUUDLLUUUURRRDDLLRDDLLUURRRUULDRDLL',
'LLDLDRUUULDRRRULDLLUULLDDRRRDDLLLUDRRURURUULRDRRDLDLRDLL',
'ULLLLLLLLLDULLLLDDRRRRRRRRURRRDDDLLUULURDLLLURURRRLUURRDDLLDDLLLLLURRLURRRRLLLLLLLDRRRULLLLLDRRRRLLLDRRRRRRRR',
'DDRDDLDRRRRRRRURRDLUUUUULLDLRUULDRDDDLDULLDDLLUUULUURRRRDDLDDLDLUDRRRRUULULDDURRDDLLLRUURRRUULRUULDLDDUURRDDDLLULDDLDRRLUURRRUULULDDURRDDLLULDDLDRUURRRURLUURRDDDDUURRUULLLLULDRDLULDDURRDDLLULDDLLLDRURRURUUULLLLDDDDUURDD',
'URURUUUUUULLLLLLDDLDDRUUDDRDDLUUDDRRRURRDRUUUUUDLLUULLLLLLDLLURRRRRRLLLLLDDDLUDLLURRDLDDRDRRURURRDRRRRDRUUUULLLLUULLLLLLDURRRRRRURDDDRRRDDDLLLLLULLUURUDLDDDLDLLULUURRUURURRRRURDLDRULLLLLDLLURRRRRRURDDULLLDDLDDRUUUDLDDDLDLLULUUURUURRRRRRRRDDRRDDLDDDLDLDLDLLURUUULUUUUUDDDDLLDLLULUURRUURURRRRRLLLLLDLLURRRRRRURDLDRLDRRLUULLLDDDDDRRRRRDRUUUDLDDDLDLDLDLUUUULULLDRDRUUUUUUDDDDRRRRRDRUULDDDLDLDLLUUDDDLLLULLUULURRRRLLLLUUULURRUURRRRRRURDDLDRUULLLDDLDDDDDRUUUUUUDDDDDLLLLLUUURRUURURRRRURDDULLLLLDLLURRRRRRURDLLLDDDDDRRDLDLUUUUUUDDDDDLLLLLUUURUUURRRRRR',
'DRRRRRRUULLLDURRRDDLLLLLLUULLDDRRRLUURDRDDDRDLUUURRRRUULLLDURRDLDLRUULDLDDDRDDLLURUUUULLDRURDDDDLDDRRULUUUULUULLDLDRRRURDDDDDRDLUUUUUURRDLULDDDDUUUURRRRDLLLULDDDRDL',
'LDDDLLDDRRUUURRDLRRRDDLLDDLLDDRRUULDLUUURDDUUUURRRDDLLRRUULLLDDLDDRRUDLLUURDUUURRRDDLLRRUULLDLDLLLUURRLLDDRRRRUUUUULLDDRDRDDLLLLUURRUUURDRDDRRDDLL',
'UURUULLLLLLLLLLLDDDDDDDRRRRRRRRRRUULLUULLDDLLUULRDDRRUURRDDLRUULLDLDLLURURRDRDLLRRRRRDDLLLLLLLLLLUUUUUUURRRRRRRRRRRDDLDLDURURUULLLLLLLLLLLDDDDDDDRRRRRRRRRRUULRDDLLLLLLLLLLDDRRRRRRUDLLLLLLUUUUUUUUURRRRRRRRRRRDDLDLDDRDDLLLLLLLLLRRRDURRRRRRUULUURURUULLLLLLLLLLLDDDDDDDUUUUUUURRDLULDDDDDUUUUURRRRDLLLULDDDDUUUURRRRRRDLLLLLULDDDUUURRRRRRRRDLLLLLLLULDDUURRRRRRRRRRRDDLULLLLLLLLLULDRRRRRRRRRRDDLDDRUUURULLLLLLLLLLRRRRRRRRRDDDDDDLLLLDDRRUDRRUUUUUUDDDDDDLLLLLLLLLRUDRRUULLLRRRRRRRRLDDRRUUUULUURDDUUURUULLLLLLLLLLRRRRRRRRRDDDLDDRULDLLULULLDRRLDRRLULLLDRRR',
'RDRRDDDRRUULUURUULLULLLLDDUURRRRDRRDDLDLLLULLLLLLDLUUUDDRRRRRUUURRDLULDDUURRRRDRRDDLDLLLULLLLLLDLUUDRRRRRUUURRRRDLLLULDDURRRRRRDDLDLLLULLLLLLRRRRDDDDLLLURRDRUUUURRDRRRDRDDLLLLULLDLLURDRUUUDDRRDRRULLLLRRDRRRRUULULLDULULLLLLRRRDDDDLLURDRUUUDDRRDRRULUULULLLLDLURRRRRDRDDLLLDLLURDRUUUDDRRRUULULLLLULLRDRRRRRDRRRDRDLLLLLLDLLURDRUUUDDRRRUULULLLLDLLUUDDRURRRRRDRRDRDLLLLLDLLURDRUUUDDRRRUULULLLLLRRRRRDRRRUURULLLLULLDDUURRDRRRDDDLLLULLLLULDRRRUUURRDLULDDURRRRRDDDLLLULLLLDLUUURUL',
'ULULULLLUUUURRDRDRDRDRDRDRDRUUUUURULDLUUUDDRRUUULLLLLRRRDDDRDDDDDLLURDRUUUURULDLUUUDDRRUUULLLLRRDDDRDDDDLLLULULULULUURDRDRDRDRDULULULULLDRDRDRDRDRRDRUUUURULDLUUUDDRRUUULLDLLUURDRDDDRDDDDLLLULULULUURDRDRDRDULULULLDRDRDRDRRDRUUUURULDLUUUDDRRUUULLLULDRRDDDRDDDDLLLULULUURDRDRDULULLDRDRDRRDRUUUURULDLUUUDDRRUUULLLRDDDRDDDDLLLULUURDRDULLDRDRRDRUUUURULDLUUUDDRRUUULLDDDRDDDDLLLUURDLDRRDRUUUURULDLUUUDDRDDDDLLUULLLUUULLLLUURDLDRRURDLDRURDLDRURDLDRURDLDRURDLDRRDRUUUURULDLUU',
'UDDDURDUUUDRDDURURDRDDURDLUUURUUDDLLURUDDLLLURRDRUDRUDDDULLLDRURDULLLLLLUUDLDLULUUDLURDDDLDDUURRDLDUURRRDLLUURULDLUDDDULDUUU',
'ULULULLDLDDRRLLLLLDDRRRRDRRULUULLLLLDDRRRRDRULLLLLUURRRUURURRDLRRDRRULLRDDDDLLDLLULLLLUURRRRRUDLLLLLDDRRRRDRRULUULLLLLDDRRUDLLUURRRLDDRRDRUU',
'LUUUULDRDDRUDDRRUULRDLLDLUUULUURDDUULLLDDRLURRURD',
'DRRRDUUURRRDDDDLLLUULLLUURRRDDLLULURDDRRDDRRRUULLLRRRUULDRDLDRDL',
'DLLLRUULLLLDULLLDDRRRUURRRDRDRRULLRRULLLLLLDDLLLUURRRRRLLDDLLULURRRRLDDLULURR',
'ULURURRRRRRDDDLLULLLRRRDRRULRUULDDRDLUUULLLLLDLDDRURRRRRURDUULLLLLLDLDRRRRRRUULLDULLLDDRRRRLUULLDLDRRRUURRDD',
'LDDDDRRRULLDRRRRULLUURUULDDDDRDLLLULUUURRLLDDDRDRRUUURUULDDDDUUULLLDLLURRUULDDRDDDRDRRUUUULLRRDDDDLLULUUULUURDDDDUULLDRURDURRRDDDLRRRDLLL',
'RRRLLLUUURRDDRDLURRRDLRDDLURUULLLDDRRULULUULLDDDDRRULDLUUUURULDLURULDLURULDLUURULDDRRDDDRRRDDRDRRULLDLLDLUUUURULDLURULDLURULDLURRDDDRRRDDRDRRRRULLLLDLLDLUUUURULDLURULDLUUULDRRDDDRRRDDRDLLDLULLDLLURRRRUUURULDLURULDLURULLRRDDDRRRDDDLDLULLLLUURDLDRRRRUUURULDLURULDLURULDLUUDRRDDDRRRDDDLDLUUUURULDLURULDLURULDLURRDDDRRRDDRRRRRRRDLLLLLDDRULULLLDLUUUURULDLURULDLUURDDDRRRDDRRRRDLLLLLDLUUUURULDLURULDLURULRDDDRRRDDRRRRRDDLLDLURULLLLDLUUUURULDLURULDLURRDDDDDDRRRURRDDLURULLLLDLUUUURULDLUUDDRRRDDRRRRUURRUULLDDDDRDLLLLLLDLUUUURULDLURULLRDDRRRDDRRRRUURRULULDDDDRDLLLLLLDLUUUURULDLURULDDRRRDDRRRRUULLUUURURDDDDDDRDLLLLLLDLUUUURULDLUDRRRDDRRRRUULLUULULUURDLDRRRURDDDDDDRDLLLLLLDLUUUUUDRRDDRRRRUUUUUULLDLLUURDLDRRRURDDDDDDRDLLLLLLDLUUUURULLDRRRDDRRRRUULLUURURDDDDDRDLLLLLLDLUUUURULDRRDDRRRRUULLURURDDDDRDLLLLLLDLUUUU',
'LRUDRDRDLLLULUURURRDDDULLDDRRUULUDD',
'URDLULLLDLLURRDDRDDLDLLUUUDDDRDDLUURRURUULDUUULLLDRDDRRRDRULLLLUURURDDULLDDRRURDRDDDLLUUDLLDDRULURLUUUDRRDRURRRDDRDLLLLLUUDLLDDRULURLUURRRLUUURRRDRDDDDRDLLLLLUUDLLDDRULURLUURRUUULLLDRRURDURRRURDDDDDDRDLLLLLUUDLLDDRULURDRU',
'ULLUURRUDLLDDRRUUDDRRRDRRULLLLDLULLUURRRRRRDULLLLLLDDRRUDRRRDRRULLLLDLULLUULLDDRRRRRRRDRRULUULLLLLLDDRRUDLLUURRDDRRRDRRULUUUULLLULLDRDDLLDDLLUURRDDRRUDRRRDRRULLLLDLURRRRUUUULLLULD',
'LULLDLUUUUUDDDDDLDDRRUDLUUUUUUDDDRRRDDLLDLUUUUULURDDDRRRDRRURRDLLLRDLLLLDLUUUULURDDRRRDRRRRDRRDRRUURUULDLLLLDDRRULLLLLDLLLDLUUURRRDULLLUURUUDLRRRRRURRDDDDRDRDDRRULDLURRURUULDLLLDLLLLDLLLDLUUURRRDULLLUULUUDRDRRURRRURRDDDDRDDRRRURULLLLDLLLLDLLLDLUUURRRDULLLUURULRRRRRURRDDDDRDDRUDRRUULLLDLLLLDLLLDLUUURRRDULLLUURURRRRURRDDDDRDLLLLDLLLDLUUUULUURRDLULDRDDRRRDRDLRDDRRULDLULULLDLUUUUURULDDDDDRUDRRUULLDLUUDRRRDRRRRUUUUULLDLLLDLLDDRRRDRRURLDDLLLLDLUUUUURRURRRURRDDDDRRRRUULLDURRDDLLLDLLLLDLLLUURRDULLLUURRURRDLLURRRURRDLLLLRRRRDDDRDLLLLDLLLDLUUUUDRRUDRDRDLLLDLUUU',
'LLULUURRRUUURRRDRRRURRRDDLUUDDDLLLLLLDDDRURUDLLUURRRRDDDRRUUUURUULLLDLLLULLLDDDRRLLLLLDDRULURRRDLULLDDRULURRDRUUURULLDLUUDRRRRRDRRRURRRDDLDDDDLLUUULLDDLLUULLDLLURDRUUURULLDLURRDDDRRDDRRUULLLLDLLURDRUUURULDLUUUDLDRRDDDRRDDRURULLLLDLLURDRUUURULLDLURRRRRDLLRRRRRURRRDDLDLLLLLLLLUURUUUURRRRRDDUULLDDRDULUULLLDDDLDDDRRRRRRRRURUULLLDLLLLLLLUUDRDDDDLLURDRUUURULDLURRUUURRDLULDDURRRDRDRRRRDDLURULLLDLLLLLRULLLLRRRUURRRDRDRDLURRRDDDDDLURULLLLLLLLUURULLRDDDDLLURDRUUURULRUUURRRRRDDLDDLLLLLDDRRRRRRRDDDLUURULLLLLLLDLLURDRUUUDDRRRRRRRRUUULLUULLLLULDDURRRDRDRDLLLLLRRRRURRRRUULDRDLLLULDRDLLLL',
'RRRURURURRDLRDDLURDDDLUDLLURDRRUUUUULLLDDDUUURRRDDLLRRUULLLDDLDLLLLUURUUURRRRRRRDDUULUURDRRRLLLLDLLLLLLDDDLDDRRRRURUURRRUULURRRURRDDDUULULDDDUULLDDDLLLDDRRRUUUULURRRURDDDUULLLDDDDDLLURDRUUUULURRRRLLLDDDDDDDDLLURDRUUUUUUULURRRURRDDULULDDULLDDDDLLLURRDRUUULURRRRLLLDDDDDDDLUULLLDLLURRRRRDRUUUUULURRRURRDLULDLLDDDLLDRDRUUUULURRRURDDULLLDDDDDLLLLLUURRRRDRUUULURRRRLLLDDDDDDDDLLLLUUDRRRDRUUUUUUULURRRURDLLLDDDLLLLLDDRRRRDRUUUUULURRRLLDDDDDDDLLLULURRRDRUUUUULURR',
'RDDDDLLLLLUUUULURRLDDDDDRRRDDLURURRUUUUUULLLLDLDDDDDRRRLLLUUUUURURRRRRURRDLDDRDLLRUUULLDDDDDRRDDLLLLULLLUUUUURURRRRRURDDDRDLLRUUULLLLLLDLDDDDDRRRDRRRRUULLUUULLLULURRRRRURDDDRDLLRUUULLLDULLDDRRLLULLDDDDDRRRUULLRRDDLLLUURRRDDDDLURRRUUDDLLURDRULLUULLLDDRRRRLUULLLUULURRURRRDDLLULURRR',
'LLLURDLLDDRRUURRUUULLLDDUURRRDRRULLLLULDLLDLLURRRRRRRDDDLLDDLLUULUUDDRDDRRUURRUUULLLLLDDDRRRLLLUUURRDDUULLDDDRDDRRUULUUURRRDDDLRUURRULLLLULDDDUULLDLLURRRRRRRDRRULLLLULDD',
'UUULLLLDLDDDRRULDLLLUURRURURRRRDDDLLLRRRUUULLDRULLLDLDLLDDRRRRURRRUURULLRDDDLLLDLLLLUURRURRRRURDLLLLLDLLDDRRUDRRULDLLLUURDLDRLUUURRRRRRLLURR',
'ULLLLUURDLDDDRDLULLLUURRLLDDRRRUURUULLDURDDDDLLLUURRLLDDRRRRDDLLUDRRUULUURRRDRRULLLLUULLDDLLDDRR',
'RDRRRDRRULLLLDLLLDDRDRRUUULLLUURRDRRRDDLRUULLLULLDDDDRDRRUUULRDRRUULLDDDDLLULUUUURRDRRRDRRDLLLRUULLLULLDDDDRDRRUUUDRRUULLDDDDDDRRUULRDDLLUUUUUDDDLLULLDRRRRDDRRUULRDDLLUUUURRRRUULL',
'RUDDDLLLULUURURRRLLLDLDDRUDDRRRUULLUDRRDDLURUUURRDRDDLDDRURRDDLDLLLLULUURUUUURRDRDDUULULLDDDDLDDRDRRRRURUULLULDRUUULUURDDDDUULDUULLDDDDLLLULUURURRRRLDDDDLDDRDRRRRURUULLUUUUULDDULLLLLDLDDRURUDLLURURRRRLDDDDLDDRDRRRRURUULLUUUUULDRDDDDRRUUUUUULULLLDLLDURRURRRDRDDDDDRRDLLLRDDLDLLLLULUULLUUUURRRRRURDDDUULLLLLLDDRULURRRRRURDDULLLDDDDLLUUULURRRRRURDLLLLLDDDRDRUUUDDLLUUURRRRLLLLDDRDRUUDLLUURRR',
'URRRURURUULUUUULDRDDDDLLDLDDRRURURULDDLDLLUURUULDLLLLDLURRRRRUUULUURDDDDRDLLLLLLRRRRRUUUURRURDDDDRDDLULLLLLLLDLLUURDRRRRRUUUURRRDDLURULLRDDRDRDLLLLLLLLLRRRRRUUULUURDDDDRDLLLLLULLDDRUUDRRRRRRRRDDLDLLUURULLLLLULDRRRRRDDDRRDRUUURULLLLLLLLDLURRRDRURRRRDDDLLLUURULLLLLLRRRURDRRRRUUUULLLDDDRDLLLLLULDD',
'UUULULLDDRDDLLLUUUUUUURRRRRRRDRDDLUUDDRRDRRUUUUUUULLLDDDLLLLLLLLULDDDDDRDDDRRRUUURRDLUUUUDRDRRUUULLLLLLLLULDDDDDRRDDDRRRUULURDRUUUUDDRRRUUULLLLLLLLULDDDDRRDDDDRRRUURRULUUUURRRDDDLLDLUUUDDRRRUUULLLLLLLULDRRRRRDDDDLLURDRUUUDDRRRUUULLLLLLLLULDDDUURRRRRRRRRRUUURRRDDDDDDDLLULLLLDDRRDRRULLLLLUUUUDDRRRUUULLLLLLLLDDDRDDDDRRRUURRDRURRDRRDLDLUURULLLDLUULUUUURRRDDDLLDLUUUDDRRRRRDDLDDRRULDLURULLLDLUUDDRRURRDDLURUUULUULULLLLLLLULLDDRURRRRRRRRDDDLLDLUUUDDRRRUUULLLLLLLULDRRRRRRRRDRRDDDDLLLDLUUDRRRDDRRULDLURUURRUUUUUUULLLDDRDLLLLLLLLDLLUURDRRRRRRRDDDLLDLUUUDDRRRUUULLLLLLLULDDDUURRRRRRRURDRRDDDDDLLLDLUUDRRRRUULLLLDLUUUDDDDRRRRDDRRULDLURULLLDLUUDRRRRURRUUUUUUULLLDDLDLLLLLLLULDDURRRRRRRURRRDLLLLLLLLLDLURRRRRRRRDDDLLDLUUUDDRRRUUULLLLLLLLRRRRRDDDLLDRDDDLLLUUUUUDDDDDRRRUURUUUUDDRRRUUULLLLLLLRDL',
'RDRRDDLDLLULRRUDDRRDDLURUUUULLDDLDDRUUUURRDDDLLRRDDLULUUUUULLDLLDDDDRRRRUUUUULLDRURDRRDDDLRDDLU',
'LDDDDDDDDDUUUUUUUUURRDDDDDDDRRDRRURRUUUUURRRDDDDDDDDLLLLLLLLLLDLLURRRRRRRRRRRLLLLLLLLLLUUUUUUUUUURRDDDDDDDRRDRRULRRRUUUUURRRDDDDDDDRDDLUUUUUUUUDDDDDDDLLLLLLLLLLLUUUUUUUUUURRDDDRDRRDDLURULDDRDRRRUULDRDLULRRUUULDDULRRUUULDDURRRURRDLLLLRRRDDDDDDDDLLLLLLLLLLLUUUUUUUUUURRDDDDDR',
'RRRRLLUUUURRUURDDDDUULLLLLUURDRRRURDDULLLLLDRRRRLLDDLURUULLDRRRLDDDDLUUURUULLDRURDDLDRRRLLDDLLLULUUUUULLLDDRDDDDRRRRRRRLLLLLUUURDDLDRRDRUUUURUULLDRURDDLDRRLDDLLLLLLDLLURRRRRRDRUUUURUULLDRRDDDDLLLLLLUULDRRRURDLDRRDRUUUURUULLDRURDDLDRDDLLLLLLDLLURRRRRRRRLLLLUUUUUULLDDDDUULDDDRRRURDLDRRRLLLLLDLLURRRRRRDRUUUURUULLDRURDDDLDDLLLLLUUUUURURDDDDDLDRRRDRUUUURUULLDRURDDLDDDLLLLLUUUURURDDDDLDRRRDRUUUURUULLDRURDLDDDDLLLLLUUURURDDDLDRRRDRUUUUULUURDLDR',
'DLULDUULLLULUURDRRDDDDRDLULDURRRRDRRULLLULLUUULLLDLDRRRLLUURRRDDDDDRULUUUULLDLDRRLUURRDDDRDDLLURDRULUUUURRRUULDRDLLLLULDDLDRRLUURRDDDDRDLUUUUURRUUUURRRRRDDDDDLLDDUURRUULLLLULDRDLLLLULDDLDRRLUURRDDDURDDLUUUURRUUUURRRDDUURRDDLDLLLULDRDLLLLULDDLDRRLUURRDDDDUUUURRUUUURRRDDRDLLLULDRDLLLLULDDLDRRLUURRDDDUUURRUUUURDDUURRDDDLLULDRDLLLLULDDLDRRLUURRDDRDDRRDRRRULLLLRUL',
'LDDDDLLUULDDUURUUULLDRDDDUUUURDDDDDRRUUUUULRDDDDDLLUUUURURDDDDUUULLDRURUUULDDRUUUULDDUULLDRURRDDLURULLDLURRRDDDDLUUURULLRRDDDDDDDULUUUUURULDDDDDLLLLDDLLUURRRRURDDDDURUUUUURULLURDDDDDLLLLDDLULURRRRLLLLUURDRRRRDDDRDUUUUUUURULDDDDLLLLLLDRRRLLUUURDLDRRRDDDUULLDDDDLUUULURRRRURDDURUUUDDLLLLUUUULDLDLLDDDRRRRRLLLLLURRRRRRDDULLLLLLDDRULURRRRRRRLURRDDDUURUUUULDDDLLLLUUULDLLDLDRRRRLLLDDDDRUULURRRRLURRDLLLLLLLDLLURRRRRRRRRURDLLLDDDDLUUULURRRRRRUUUUDDDRDLLLLLLLLLLLLDDDRUULURRRRRRRRRRLLLUUULLDLDRRRRRRRDDURUUUDDDLLLLLLLLLLLLDDDDDRUUURRLLULURRRRRRRRRRLLLLLLLLLURRRRRRRRRRDRUUDLLLLLUULDLDRRRRRRDRULLLLLLLLLLLURRUULDDLDRRRRRRRRRDRUUUDDLLLLUULLLDLDRRRRRRRLLLDDDDLLLUULURRRRRRRRUUDLLLLULLLLLLLUURDLDRRRLLLUUUURDDLDRRRRDLDRRRRRRRRLLLLUUULLDDLDRRRRRRDRULLLLLLLLUUURULLDLLUURDLDRRDDLDRRRRRRRRRLLLUUUULLDDDLDRRRRRLLUUUULLLLDULDLLUURDLDRRRDDLDRRRRRRLUUUULLLDDDLDRRRRLLLDDDDDLUUULURRRRRRRRLLLLLLDDDDLLUUULURRRRRRRRLLLLLLLLLDDDDDRUUUULURRRRRRRRLDDDDLLLLLULLDDRUUUULURRRRRRR',
'LLLRRUURRRRUULLUULLDLLLLDRLDDRRDDLDDRRRUDLLLUURDUUULULUURRRURRUURRDLLRDDDRRRRRRDDDLLDLLDLLULLLRUURRRRUURRDDUULLULDLUULLDDRDULULLLLDDRUDDRDDRRDDLLLUUUDRRRRRDRRULLLLLLULDDUUUULUURRRURRUURRDLULDRDLLRRDRRDDDRDULUURRRRDDDLLDLLLLLLLLULDRRRUURRRRUURRDDUULLDDRDULUURRRRDDDLLDLLLLLLLLDLURRRUURRRRRDRDLLLLLLLRUURUULULLLLUURDLDRRRLLLDDRULURRLDDDRDDLUUUULURDDDDDRRRUURRRDURUULLLRRRRRDDUURRDLRDDLLDLLLLLLLLULDRRRUURRRRRDRDLLLLLLLLRRUURUURRRRRDDURRDDLLULDRDLLLLLLL',
'URUUULLLDLDLLDLLLLURDRRRUULLDURRDDLURRRURRURRDDDLLULLLLURRLLDDLLUURRDRRRRDRRUUULLDURRDLRDDLDDLLULLDURRDLDDLLUURURDRRRRDDDLLUUDDRRUUULLLULLDRRLLLDDRRULULLLDDRRURULRURRDLRRDDDRRUULRDDLLUU',
'RRRUUULLDDRDRDDDLLLLLLULUURUUURRDDRRUURRDDDDUUUULLDDRLLLUULLDDDLDDRDRRRRRRRULLLLRRRUULULUURRDDDDUULLLLUULLDDDLDDRDRRRRRRRULLLDLLLLULUURURRRDRRURDDULLLULLLDLDDRDRRRRRRRULLDLLLLLUURURRRRURDDULLLLLDLDDRRRRRRRULDLLLLLLULUURRRRRRURDDDRDLLLLRRRUUULLLURURURDDDDDRDLLLRRUUULLURURDDDDRDLLRUUULLLLUURRRURDDDDDRDLUUULLLLLLURRRRRURDDDDUULLLLLLUURRRRRURDDDD',
'RDDRRUURRUULDRDLULDRUUUULLDRURDDRDLUUULLLLDRRRURDDRDDLUDLDDRRRRURRUULLLLRRRRDDLURULLLRRDDLDLLLLUURRUDLLDDLLUURRRLLLLLDRLLLURRRRRRDDLLULURDDRRRDDLUUUDRRRRUURULL',
'DLLRRUULDLLULLDRLUULLDRURDRDDLLURUULDRRRRDDLRURRDLLRRUULLLLLULLDRRRLDDLURUULLDRR',
'URRRDDRRUUDDLLUULLDRURRUULLDDRRURRRDDRRUULLLLRRDDLDLLLULULLDRRUUURRDRRRDDRURULLLL',
'LLLDLLURRRRURRDLDDDLLLLDDRRDDDRRUUUUUDDDDRRRRRDRRULLLLLLRRRRRUURUULDDDULLLUUURDDLDRRLUULLLLLLLLDDRRDDDRRUUUUDDDDLLUUULLUURRRRRRLLLLLLDDRRDRLDDRRUUDRRRRRDRRULLLLLLRRRRRUURUULDDDULLUUULDLLLLLLLDDRRDRRUUDDLLULLUURRRRLLLLUURURRURRDLDDDLLLLUURURRURDDULLDLLLURRRRURDLLDLDLDRRLLDDRULURDDRDRRUUDDLLDDRRUUUDDRRRRRDRRULLLLLLDLUUDRRRRRRUULLLURUL',
'URDDRRULLULLDRLDRDDLDDRUUDDRRRUULDRDLUUUURUULDD',
'RURRRURRRULDLLUURDLDRDDDRDRRULLLRRURDRUUDDLLLLUUUURRDDDRDDLLURDRUUDLLLULLDRRRRDRULLLUUUUUUULDRDDDDLLLLULUURDRDULLDRDRRDRRUUUUULLLULDDLDLURRURRRRDDLURULRDDDDDLUUUUDDDLLLULUURDRDULLDRDRRDRRUULDDRDLUULLLUURDLDRRDRRUULDRDLDRRDDLLLLLUUUURUULLDRURDLDRRLLDDDDRRRRRUULULUURUULDDDDULLLDLLUURUULLLDDRRRRURDLDRRLLDDDDRRRRRUULUUULDLLLUUULLDULLDDRRRRURDLDRRRURDDULLLLUUUUULLDDDRRDDDDDDRRRRRUURRRURUUULLLLRDDDDLDDLLLLLUUUURRRUUURDDDUURRRRRDDLURULLLLLULDRUUULDDRDDDLLLLUUUURRLLDDDDRRRRUUUUULDRDDRRRRDDDLDLUUUDDRRUUULLLRDDDDLDDLLLLLUUUURRRRUURRDLURRRDDLDLUUDRRUULLLRDDDDLDDLLLLLUULLUULURRRURDLDRRRLLLDDLLLUURUUULLDDRRRRURDLDRRLLDDDDLLDLUUUUURUUULLDDRRRRURDLDR',
'DDDRRUUDDLLUURUUULURRLDDDLDDDRRURURRURUUUDLLLURRRDDDDLLLURRDRUUDLLLDDLDLLUURUUUURRRRRRDLLLULLLDDDLDDDDRRRURUULURRDRUUDLLDDDLLLLUURUUUURRRRRRDLLRDDLLDDDRUULURDRUUDLDDDLLDDRUUDDRUUUUDDDRRDDRRULDLURULLRDDRRRRUUUUULLDLDURUUUULLULLDRRLDDDLLURDRUUDLDDDLLLLLUURUUUURRRRRRDLDDLDDDLUULURRDRUUURUULLDRURDLDDDLLDDDDDRUUUULURDRUUUURULDDDDLDDDDRRURURUUUUURULLRDDDDDDLDDLLLUUUURRRLLLDDDDRRDDRRULDLURULLRRUURUUUUURULDDDDLLLLLDDDDDRUUUULURDRUUUUDDDRRRDRRDDDDLLLDLURULLRRUURUULLLLLDDDDDRUUUULURDRUUUDDLDDDLLLLLUURUUUURRRRRDDDRRRDRRDDLLULDDLDDRRULDLURULLRURRUUULLLLLDDDDDRUUUULURDRUUUDDRRRDDDRDRDLLLDLURULLRURRUUULLLLLLLRRDDDLLUULUUULURRRRLLLDDDDRRULDLUUULURRRLLDDDRDDDRUUDDDDRRUUUULURDRUUDLLLLDLUUULURR',
'LLULLDDDDRULLLDDDRRRUDLLLUUURRDDRDLLLLLLRRRRRUUUUUURRDLULDDDDDRDLLLLLRRUUURRRULUURRDLULDDDDDRDLLLLRRRUUUUURRRDLLULDDDDRDLLLULDRRRURUULUURRDLULDDDDRDLLLDLLLRRURRRRUUUUUUUULDDDDDDDRDLLLULLLRRDRRRUUUUUUUURRDDDRDLLULDDDDRDLLLDLLRURRRUUUUUUUURRRRDLLLULDDDDDDDRDLLLULLRDRRRUUUUUUURRRRRRDDLLLLLULDDDDDRDLLLDLURRRUUUUUUURRRRRDRDLLLLLULDDDDDRDLLLULDRRRUUUUUUURRRRDRDLLLLULDDDDDUUUURRRRRDDDLLUUDDDDDDLLUULLLRRRUUULUURRDLULDDDDRDLLRUUULLDDDRRUUUUUUURRRRDDLLLULDDDDDRDLL',
'RRDDDRRUUUUURRDDUULLDDDDDLLUUURLDDDRRRRRUULUUULLDDDDUULLDDDRRRRDDDLURURUUDLLLUUULLLLLUULLDDLDDRDRRRRRRRRRDRULLLLLLLLLLDDRULURRRRRRRRRLLDRRDDLLLULLDRRRDRUURUULLDRULLLLLURDLLLDDRULURRRRRRRLUUULLDDLDRRRUUURLUULDURRRDDLLDDDLLUUURURDDDDLLLLLLLULUURRRRRRRURDDDUULLLLLUULDLDRRRRRRURDDULLLULDLLUURDLDRRRRRURDLLDDDDDLDRRRDRUU',
'LDDDDLLLUUUUUUURRRDRRRDDRDDLRUULUULLLUURRDULLDLLLDDDDDDDRRRURRURRUULUULULLLLRRRRDRDDRDDLLDLLDLLUULLLUUUUUURRDRRRDRULLLLDDRDDDDDRRUUUURUUDDLDDDRRURRUULUULULLLLRRRRDRDDRDDLLDLLDLLUUUULLLDLUUURUURRDDDRDDDDDRRUUUURUURULLLLRRRDDDLDDDDLLUUUULLLDLUURUUURRDDDRDDDDDRRUURUUUURULLLLRRDRRRDDLRRDDLLULLDDDLLUUUULLLDLURUUUURRDDDDDRDDDRRUUURUUURULLLLRRDRRRDDLDLLDDDLLUULLLDLURUUUUUURRDDDDDRDDDRRUUURUUURULLLLRRRDDDLDDDDLLUULLRUULLUUUURRDDDRDDDDDRRURUUUUURULLLLRRRDDDRRRDLLDLLDDLLUUUULLLDDUUUUUURRDDDRDDDDDRRUURUUUURULLLLRRRDDDLDDDDLLUUUULLRUULLUURRDDDDRDDDDRRUUURRRRRRULLRULDLUDLDLUUURULLLLRRRDDDLDDDDLLUULLLUUUUUURRDDDUURRRURRRRDDLLRDDRRULDLUDLLUURULLLLRRRDDDLDDDDLLUUUULLRUULLUURRDDDUURRRURRRRDDLLRDDLLUURULLLLRRRDDDLDDDDLLUUUUULULLUULUURDDRRDRRRRDDDLDDDDLLUULLLUUUDDDRRRUULLRRDDLLLUUDDLDDRUURRDDRRRURUUUUUULLLLDDRDLLRDRDLL',
'RDRRRULULDRDLRRRRULULDRRRULUUURURRDDLLULDDDRDLDLLUURDRRURRRURUUULLDDLLLDDDURRRRURULLLLULDDDUURRDURRDDLLLDLLULDLLURRDRRRURUULLDDRDLLLLULDLLURRDRRURDRRURUULLDDRDLLLLLURRRDRRURUURUURUULLLDDDLDDDRDLLLLURRRRRUULULDDDRDLLRUUURRRUULRRUULLLDLLDLDDRLUURURRDDLDDDLDRURRUULULDDDLLLDR']
//#：围墙   .：目标点   $：箱子    @：人物     *：目标点+箱子
var Boxworld=[
`  ###   
  #.#   
  # ####
###$ $.#
#. $@###
####$#  
   #.#  
   ###  `,
`#####    
#@  #    
# $$# ###
# $ # #.#
### ###.#
 ##    .#
 #   #  #
 #   ####
 #####   `,
` #######  
 #     ###
##$###   #
# @ $  $ #
# ..# $ ##
##..#   # 
 ######## `,
` #### 
##  # 
#@$ # 
##$ ##
## $ #
#.$  #
#..*.#
######`,
` #####  
 #@ ### 
 # $  # 
### # ##
#.# #  #
#.$  # #
#.   $ #
########`,
`   #######   
####     #   
#   .### #   
# # #    ##  
# # $ $#. #  
# #  *  # #  
# .#$ $ # #  
##    # # ###
 # ###.    @#
 #     ##   #
 ############`,
`   #######
  ##  # @#
  #   #  #
  #$ $ $ #
  # $##  #
### $ # ##
#.....  # 
######### `,
`   ###### 
 ###    # 
##. $## ##
#..$ $  @#
#.. $ $ ##
######  # 
     #### `,
` ######### 
 #  ##   # 
 #   $   # 
 #$ ### $# 
 # #...# # 
## #...# ##
# $  $  $ #
#     # @ #
###########`,
`  ######
  #    #
###$$$ #
#@ $.. #
# $...##
####  # 
   #### `,
` ####  #####
##  #  #   #
# $ ####$  #
#  $.... $ #
##    # @ ##
 ########## `,
`  ##### 
###  @# 
#  $. ##
#  .$. #
### *$ #
  #   ##
  ##### `,
`  ####  
  #..#  
 ## .## 
 #  $.# 
## $  ##
#  #$$ #
#  @   #
########`,
`########
#  #   #
# $..$ #
#@$.* ##
# $..$ #
#  #   #
########`,
` #######
##    # 
# $ $$ #
#......#
# $$ $ #
### @###
  ####  `,
`  ######  
  #    ###
  # $    #
### $ ## #
#... $   #
#...$#$ ##
#### # $ #
   #  @  #
   #######`,
`######   
#    #   
# $$$##  
#  #..###
##  ..$ #
 # @    #
 ########`,
`  ########
  #   #. #
 ##  $...#
 #  $ #*.#
## ##$# ##
#   $  $ #
#   #    #
#######@ #
      ####`,
` #######  
 #.... #  
###...$###
#  $#$ $ #
# $$  #$ #
#    #   #
#### @ ###
   #####  `,
`####### 
#..$..# 
#..#..# 
# $$$ # 
#  $  # 
# $$$ # 
#  #@ # 
####### `,
`   ######  
   # ...#  
####....#  
#  ###$ ###
# $ $  $$ #
#@ $ $    #
#   ###   #
##### #####`,
`######## 
#      # 
# #$$  # 
# ...# # 
##...$ ##
 # ## $ #
 #$  $  #
 #  #  @#
 ########`,
`  #####   
###   ####
#   $ $  #
# $   $ @#
###$$#####
  #  ..#  
  #....#  
  ######  `,
`######   #####
#    ### #  .#
#  $ $ # #...#
# #  $ ###  .#
#  $$$   $ @.#
###  $  $#  .#
  #  $#$ #...#
  ##     #  .#
   ###########`,
`     ######
 #####.   #
 #  #..## #
 #  $..   #
 #  # .# ##
### ##$#  #
# $    $$ #
# #$#  #  #
#@  #######
#####      `,
` #########   
 #   ##  ####
 # $        #
 ##$### ##  #
 #  ## * # ##
 # $...... # 
## ### . # # 
#     $###$# 
#   #    $@# 
#####$# #### 
    #   #    
    #####    `,
`      #########
      #       #
      # # # # #
      #  $ $# #
#######   $   #
#..#  ## $ $# #
#..   ## $ $  #
#..#  ## ######
#..# # $ $ #   
#..     $  #   
#  ### @ ###   
#### #####     `,
`    ####        
#####  #        
#  $ $ # #######
#   $  # #*.*.*#
## $ $ ###.*.*.#
 #$ $  #  *.*.*#
 #@$ $    .*.*##
 #$ $  #  *.*.*#
## $ $ ###.*.*.#
#   $  # #*.*.*#
#  $ $ # #######
#####  #        
    ####        `,
`######## 
#......# 
#  $ # ##
# $ # $ #
##$ $ $ #
 #  @   #
 ########`,
`  ##########
###   .    #
#   ##$##  #
# @$. . .$##
## $##$## # 
 #    .   # 
 ########## `,
`   ######
####.  @#
#  $$$  #
#.##.##.#
#   $   #
#  $.# ##
####   # 
   ##### `,
` ###### 
 #. ..# 
 #. $.# 
###  $##
# $  $ #
# #$## #
#   @  #
########`,
`    ######    
  ###    ###  
  #   #$   ###
  #   $   $$ #
  # $$ #$    #
  ##   $   $ #
###### #$#####
#..@ #$  #    
#.#..  $##    
#....$# #     
#....   #     
#########     `,
`###############
#      #      #
# $ #$ # $##$ #
# #  $ #      #
#   ##$#$##$$ #
# # # ... #   #
# $  . # .$ # #
# $#@$...# #  #
#    . # .  $ #
# ##.$###$. # #
# # $..... ## #
#             #
###############`,
`######### 
#   ##  # 
# # $ $ # 
#  *.#  # 
## #.@.## 
##$###*###
#        #
#   ## # #
######   #
     #####`,
`########       
#      #       
# $$   ###     
#  $ $$$ ##### 
## ## ...    ##
 # #@#...###$ #
 # # $...     #
## # $...$ # ##
#  ##### ### # 
#      $   $ # 
###########  # 
          #### `,
`   ##### 
   # @ # 
   #$$$# 
####   # 
#   .#$##
# $.$. .#
#  #.#.##
######## `,
`############
#... #     #
#..  # ##  #
#..     #  #
#..  # $## #
#... #$ $  #
######  $$ #
 ##  $ $$  #
 #@ $$$  # #
 ## $ ##   #
  #        #
  ##########`,
`#########  
#       #  
#  $ $ $#  
## #$## #  
 # .. ..## 
 ##.. .. # 
  # ##$# ##
  #$ $ $  #
  #      @#
  #########`,
`#####      ####
#@  ########  #
## $       $  #
 # # #  ####  #
 #  $   ####$##
 #$ ## # $ $ # 
## $  $#     # 
#   #      # # 
#   #####$#### 
#####   #   #  
    #...  $ #  
    #....#  #  
    #....####  
    ######     `,
`     #####
 #####   #
 # .. $# #
 # #.*   #
## *.#$ ##
# $  $  # 
#   ## @# 
######### `,
`##### #######
#   ###  #  #
# $     $ @ #
## #$##.##  #
 #  ...*. $ #
 # $# #.# # #
 ##    $    #
  #  ########
  ####       `,
`         ###   
    ######@##  
    #....#$ ## 
    #....# $ # 
    #.... $  # 
    # ...#   # 
###### ##### ##
# $ $   $  #  #
#    $$   $ $ #
### $ $ $  ####
  ##   $ $ #   
   #  ######   
   ####        `,
`   #####   
 ###   ### 
##  @$ $ # 
#  ## ## ##
# $.#.$   #
# #.#*#   #
# $...  ###
###$# ###  
  #   #    
  #####    `,
`      ####     
      #  ######
      #    #  #
      # $$    #
#######$#  #  #
#  #. .. ###$##
#  #.#*.$     #
#  #.#.*# #   #
# $$....# #####
# @$ # ## #    
# $$$#    #    
#    ######    
######         `,
`####           
#  ###         
# $  ###       
# $ $  ###     
# $ $ $  ###   
# $ $ $    #   
# $ $  #   ##  
# $  ## $$$ #  
#@ ####     ## 
## # #.$$$$$.# 
 # ###.......##
 #   .*******.#
 ####.........#
    ###########`,
`#######    
# @#  #####
# $$  $   #
#  #.##$# #
##$#...   #
## ...##$##
#  ##.##  #
#  $  $   #
#  #   #  #
###########`,
`   #####   
   # @ #   
   # $ #   
   #$.$#   
 ###.$.##  
## .$.$.###
#  $.$.$  #
#    .    #
###########`,
`#############
#  $ $ $.*..#
# $ $ $ *...#
#  $ $ $.*..#
# $ $ $ *...#
#  $ $ $.*..#
# $ $ $ *...#
#  $ $ $.*..#
# $ $ $ *...#
#  $ $ $.*..#
#@$ $ $ *...#
#############`,
`             # 
            ## 
           ### 
          #   #
   ######## # #
  # $ $ $ $   #
 ## #.#.#.#@$# 
###.......   ##
 ## # # # #$## 
  # $ $ $ $   #
   ######## # #
          #   #
           ### 
            ## `,
`#######  
#  .$ ###
# .$.$  #
#*$.$.@ #
# .$.$ ##
#  .$  # 
######## `,
`         #####  
         #   #  
########## * ###
#          .   #
# $$$$****$...@#
#          .   #
########## * ###
         #   #  
         #####  `,
`     ####    
######  #####
#@$    $  $ #
#$### $ # # #
#  #  # $   #
# $#    # ###
#  $ #$#   # 
#......... # 
########   # 
       ##### `,
`  #######  ####
  #    $  ....#
###   # # ..#.#
# $$ #  # ....#
#    # $# ..#.#
##$###$  ###  #
 #  #  $ $    #
 #    $ $  #$ #
 # $## $ ##  ##
 ## #### # @## 
  #   #  $ ##  
  ###     ##   
    #######    `,
`###########
#    #    #
# $@$$$$$ #
#         #
##### #####
   #.  #   
   #.  #   
   #...#   
   #.  #   
   #####   `,
`   #####  
   # @ #  
   # $ #  
 ### . ###
 #   *   #
 # ***** #
 #   *   #
 ###$*$###
   # . #  
   # * #  
   # . #  
   #####  `,
`##############
#.           #
#.$ $ $ $ $  #
#.#########  #
#.#.* $ ..$*##
#.# $ $ *.$@# 
#.#.  $ ..$$# 
#.#########.# 
#.          # 
#.#$#$#$#$#$# 
#.          # 
############# `,
`############  
#..  #     ###
#..  # $  $  #
#..  #$####  #
#..    @ ##  #
#..  # #  $ ##
###### ##$ $ #
  # $  $ $ $ #
  #    #     #
  ############`,
`       ####   
########  ####
#   ##.....  #
#  $  ##...# #
##  $  ### # #
 # # $  #    #
 #  # $  #   #
 #   # $  #  #
 #    # $ # ##
 ####  # $  # 
    ##  # $ # 
     ##@#   # 
      ####### `,
`####      ####
#..########..#
#*.*.....*.*.#
# $ $ $ $ $ $#
#$ $ $@$ $ $ #
# $ $ $ $ $ $#
#$ $ $ $ $ $ #
#.*.*.....*.*#
#..########..#
####      ####`,
`    #####   
   ##   ####
   # ..* $ #
#### #.#   #
#    .*.#@##
# #$##$## # 
#     $ $ # 
##  #   ### 
 ########   `,
` ######   
 #    #   
 # $  ####
 # $*..* #
 # *..*$ #
 ####  $ #
    # @  #
    ######`,
`   ##### 
####.  ##
# $.$.  #
#@$# #$ #
# $. .  #
####$#$ #
  #. .  #
  #######`,
`############
#    ... $ #
# $$$*** $@#
#    ... $ #
############`,
`##########
##       #
#   #$#$ #
# $$  .$.#
# @###...#
##########`,
` ####     
 #  ##### 
##$ ##  # 
#  $@$  # 
#   ##$ # 
###.## ###
 #...$ $ #
 ##..    #
  ########`,
`##### ####     
#...# #  ####  
#...###  $  #  
#....## $  $###
##....##   $  #
###... ## $ $ #
# ##    #  $  #
#  ## # ### ####
# $ # #$  $    #
#  $ @ $    $  #
#   # $ $$ $ ###
#  ######  ###  
# ##    ####    
###             `,
`#######
#. . .#
# $$$ #
#.$@$.#
# $$$ #
#. . .#
#######`,
`      #### 
#######  # 
#     $  # 
#   $##@$# 
##$#...# # 
 # $...  # 
 # #. .# ##
 #   # #$ #
 #$  $    #
 #  #######
 ####      `,
`   #########
   #   #   #
   #       #
#####*### ##
#   ...   # 
# # #*###$##
# $    $   #
#####@ #   #
    ########`,
`#####           
#...# #####     
#...###   #     
#....   $$##### 
#....  #  #   ##
#..#$#### #$#  #
## $  #     $$ #
#  $# @ $ $$#  #
# $ $ $ #   $ ##
#   #  $ ##   # 
######   ###### 
     #####      `,
`###############
###.#      ####
##..# $  $ #  #
#...# ## $ #  #
#.....  #$$   #
##....$    #$ #
#### #######  #
#   $        ##
#  $ #  $# $ ##
# $### $ # $$ #
#   @#  ##    #
###############`,
`       ########
       #  #   #
 ####### $$...#
 #        #...#
 # ######$#...#
## #      #...#
#  # #$ $ #####
# # $ $ $ #    
# @  $ #  #    
#####$ $$ #    
    #     #    
    #######    `,
`       #####
  ######   #
###    . $ #
# $  #$.#$##
#  #  @.#  #
## ####.   #
 # $  #*####
 # ## #.  # 
 #     .# # 
 ###$     # 
   #  ##### 
   ####     `,
`            
    ####    
#####  #####
#    $   $ #
#  $#$##   #
### #.*. ###
  # ... @#  
  ## #$###  
   #   #    
   #####    `,
`            
    ########
 ####    . #
 #  $ $ $. #
 #  .####.##
 # $.$ $ @# 
 #  .  #### 
 #######    `,
`  #####    
  #   #    
###$.$#####
#   . $   #
# ##$## @ #
#   . #####
### . #    
  #   #    
  #####    `,
` #####     
 # @ ######
 # #..*   #
 # ...#   #
##$## $ $ #
#   #$#####
#   $   #  
##### # #  
    #   #  
    #####  `,
`     ######   
   ###    ##  
   #   ##  #  
 ###$##  # #  
##     ..# #  
#  $#$#*.# #  
# $$@ #.*# ###
#  $$ #..#   #
##    #..$   #
 ###$##. # ###
   #  ###  #  
   ##     ##  
    #######   `,
`     ####### 
     #  #  # 
     #  $$ # 
###### $#  # 
#...### #  ##
#.  #  $ #  #
#.    $ $ $ #
#.  #  $ #  #
#...### #  ##
###### $   # 
     #@ #  # 
     ####### `,
`          ######
          #    #
#####   ### ## #
#.. ##### $  # #
#..     $   $# #
#..  ## ##   # #
#.. ## $ #$ $# #
#.. #     $  # #
#.. #  $ ###$  #
#.. # $ $  $ ###
### ## # $    # 
  #    #@## $ # 
  #########  ## 
          ####  `,
`     #####     
   ### @ ###   
   #  $ $  #   
   # *.*.* #   
  ## .$ $. ##  
 ### *.*.* ### 
####  $ $  ####
   ######  #   
    ##   ##    `,
` ############## 
 # @ * * * #  ##
 #$#  * *  #   #
 # # * * *     #
 # #  * *  ## ##
 # # * * * ## # 
 # #  * *  ## # 
 # # * * * ## # 
 # #  * *  ## # 
 # # * . * ## ##
## ##########  #
#              #
#   #########  #
#####       ####`,
` ############# 
 #    #  ##  # 
 #$$$ # $$  $##
 # $  #  .... #
 #  $  #$.##. #
 #  # $# ....##
##$ $  #$.##. #
# $  $ @$.... #
#   ###  ######
##### ####     `,
`     #########
     #       #
     #  $#$# #
 ######  # $ #
 #   # $  $  #
## $     ### #
#   #$####   #
#    $ ### ###
#####.. @# ## 
   #...$ $$ # 
   #...#    # 
   #...###### 
   #####      `,
`####     ####   
#  #######..### 
# $ $ $  #....# 
# $   $$ #***.# 
# $ $ $  #..*.# 
#  $ $ $ #*.*.# 
## $ $ $ .*.*.##
#  $ $ $ .*.*.@#
#  $ $ $ #*.*.##
# $ $ $  #..*.# 
# $   $$ #***.# 
# $ $ $  #....# 
#  #######..### 
####     ####   `,
`                
      #####     
#######   #     
#   ##.   #     
#  $#..  ###    
##  ...#$$ #####
 # $.#.$       #
 # $###$## # $ #
 #   #     $$# #
 ##$$# ##$#$   #
 #... $@ $   ###
 #...#$#   ###  
 #...  #####    
 #######        `,
` ####  ######
 #  ####    #
##*   * **  #
# $ *    *# #
# .   ###   #
######   #@##
# * . *  ** #
#   #   #   #
##*   * #$# #
 #  #####   #
 ####   #####`,
` ######### 
 #   #   # 
 # $$$$$ # 
## $ $ $ # 
# $  @   # 
# $ #### ##
#  #..... #
##  ..... #
 ##########`,
`   #######     
   #     #     
   # $ $ ##    
   #####..#####
######..*.  $ #
#  $@$....#$$ #
#   $ #$###   #
#####       ###
    ###  ####  
      #  #     
      ####     `,
`#####     
#   ######
# $ .. $ #
##$ ..$$@#
 #  .. $ #
 #########`,
`  #####     
  #   ######
###$#.     #
# $ ...# $ #
#@ $.#*$   #
####    ####
   ######   `,
`    #####      
#####   #      
#   $ @ #      
#  $ #.#####   
##$ ##.##  ####
 #  ..... $#  #
 # $##.##  #$ #
 #   #.##     #
 ### $ ##### ##
   # #$     $ #
   #    ###   #
   ###### #####`,
` #######
 #  *  #
 # @.$ #
 # $.  #
 #*.***#
 #  *  #
 # $*$ #
 #  .  #
 #######`,
`  #########     
  #    #  #     
### #$  $ ####  
#  $  ##..#  ###
# #  $ #..$ $  #
# $$  $#..  #  #
##  #  ...#$   #
 #$ @ #...# $  #
 #    #...$   ##
 # ##$ ###   ## 
 #   $     ###  
 #  ########    
 ####           `,
`   ########## 
####......  # 
#   .....#  # 
#  #...... ## 
## ####$##$#  
#@$  $ $   ###
# $$    ##   #
# #  $$##  # #
#   $  # $$  #
#  $  $   #$ #
####   # $ $ #
   #   #     #
   ###########`,
`      #########
      #       #
      #$ $$$  #
      #   # $ #
      #   $@$ #
    ###$ $ # ##
    #   $#$# # 
##### #  #   # 
#...  # $# ### 
#.....   # #   
#.....# $# #   
########   #   
       #####   `,
` ##### ###### 
 #   ###    # 
## $ $ #$ #$# 
#  $ @ $  $ ##
# #  ## #....#
#  ## $ #.##.#
##  $    ....#
 # $$ #$#....#
 #   #   #$ ##
 ##### $    # 
     ####  ## 
        ####  `,
`####           
#  #           
#  ##########  
#    ##     #  
#..#    $$# #  
#..  ##   $ ###
#..#  ##$# $  #
#..   # @$ $  #
#..#  # $ $   #
# .   # $ $ ###
#  #  #   ###  
#  #    ###    
#########      `,
`         #####  
        #     # 
       #  $##  #
      #  #   $ #
#  #  # #  # # #
 # #  # $ $  $ #
  ####### #$#  #
  #  $ $      # 
  #@..$ **.###  
   #......##### 
    ############`]