#将静态内容部署到开源代码库页面的简单工作流程
名称:将静态内容部署到页面

开启:
#针对默认分支的推送运行
推送:
分支:["主要"]

#允许您从“操作”选项卡手动运行此工作流
工作流_调度:

#设置GITHUB_TOKEN的权限以允许部署到开源代码库页面
权限:
内容:阅读
页面:书写
id-token:写入

#仅允许一个并发部署，跳过正在运行和最新排队运行之间排队的运行。
#但是，不要取消正在进行的运行，因为我们希望这些生产部署能够完成。
并发性:
组:“页面”
正在取消: 错误的

工作:
  #单个部署作业，因为我们只是在部署
部署:
环境:
名字: github-页面
全球资源定位器(Uniform Resource Locator): ${{步骤.部署.输出.页面_url}}
连续运行: Ubuntu-最新版
步伐:
      - 名字: 检验
使用: 动作/签出@v4
      - 名字: 设置页面
使用: 操作/配置-页面@v5
      - 名字: 上传工件
使用: 用途:用途:操作/上传-页面-工件@v3
随着:
          #上传整个存储库
小路: '.'
      - 名字: 部署到GitHub页面
身份证明（identification）: 部署
使用: 操作/部署-页面@v4
